# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor_2 = torch.rand(7, 7)
random_tensor_2

tensor([[0.6687, 0.8759, 0.5117, 0.2989, 0.7076, 0.4648, 0.8460],
        [0.7799, 0.4734, 0.0096, 0.8574, 0.4114, 0.3358, 0.4241],
        [0.3133, 0.6173, 0.1301, 0.1221, 0.7433, 0.1836, 1.0000],
        [0.6912, 0.6214, 0.8800, 0.9834, 0.7276, 0.6905, 0.4053],
        [0.6654, 0.2163, 0.7619, 0.2668, 0.5385, 0.3747, 0.4320],
        [0.3130, 0.5102, 0.8159, 0.9524, 0.2505, 0.2906, 0.5563],
        [0.8132, 0.5230, 0.3860, 0.7946, 0.6197, 0.9202, 0.6715]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_3 = torch.rand(1, 7)

# Perform matrix multiplication 
multiplied_tensor = torch.mm(random_tensor_2, random_tensor_3.T)
multiplied_tensor

tensor([[1.2727],
        [0.9341],
        [1.9029],
        [2.3976],
        [1.3065],
        [1.2050],
        [1.7223]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor_4_1 = torch.rand(7, 7)
random_tensor_4_2 = torch.rand(1, 7)

# Matrix multiply tensors
multiplied_tensor_4 = torch.mm(random_tensor_4_1, random_tensor_4_2.T)
multiplied_tensor_4

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [2]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
    print("not available for GPU")


# Create two random tensors on GPU
# torch.cuda.manual_seed(seed=RANDOM_SEED) <= wrong since tensor is generated in cpu and copy to gpu
rand_tensor_gpu_1 = torch.rand(2, 3).to(device)
rand_tensor_gpu_2 = torch.rand(2, 3).to(device)
rand_tensor_gpu_1, rand_tensor_gpu_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
multiplied_tensor_gpu = torch.mm(rand_tensor_gpu_1, rand_tensor_gpu_2.T)
multiplied_tensor_gpu, multiplied_tensor_gpu.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
print(f"Maximum: {multiplied_tensor_gpu.max()}")
print(f"Maximum: {torch.max(multiplied_tensor_gpu)}")

# Find min
print(f"Minimun: {multiplied_tensor_gpu.min()}")
print(f"Minimun: {torch.min(multiplied_tensor_gpu)}")

Maximum: 0.5617256760597229
Maximum: 0.5617256760597229
Minimun: 0.3647301495075226
Minimun: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [29]:
# Find arg max
print(f"Index of Maximum: {torch.argmax(multiplied_tensor_gpu)}")

# Find arg min
print(f"Index of Minimum: {torch.argmin(multiplied_tensor_gpu)}")

Index of Maximum: 3
Index of Minimum: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
RANDOM_SEED=7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
rand_tensor_10 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
rand_tensor_10_squeezed = torch.squeeze(rand_tensor_10)

# Print out tensors and their shapes
rand_tensor_10, rand_tensor_10.shape, rand_tensor_10_squeezed, rand_tensor_10_squeezed.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))